name: earth-analytics-python
channels:
  - conda-forge
dependencies:
  # Core scientific python
  - numpy
  - matplotlib
  - python=3

  # Geo stuff
  - rasterstats
  - geopy
  - cartopy
  - geopandas
  - rasterio
  - contextily
  - pysal

  # Jupyter Environment
  - notebook
  - ipython
  - jupyter_contrib_nbextensions

  - pip:
      # Utilities
      - download
      - nbgrader
      - mne
      - tqdm
      - git+https://github.com/geopandas/geopandas.git
